### ISSUE TITLE
Simplify COMPOSER_HOME env variable

### ISSUE THREAD

**Issue by matthiasnoback** [matthiasnoback/php-workshop-tools#5]
Use this:

```yaml
        environment:
            COMPOSER_HOME: /home/.composer
        volumes:
            - ~/.composer:/home/.composer
```
